name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Build Universal Release APK
        run: |
          mkdir build_env
          cd build_env
          flutter create . --org com.vngapp --project-name memo_manager --platforms=android
          cp -rf ../lib .
          cp -f ../pubspec.yaml .
          flutter pub get
          flutter build apk --release --no-shrink --no-tree-shake-icons
          cp build/app/outputs/flutter-apk/app-release.apk ../app-release.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app-release.apk
          
